Update verify-keystore.yml

diff --git a/.github/workflows/verify-keystore.yml b/.github/workflows/verify-keystore.yml
--- a/.github/workflows/verify-keystore.yml
+++ b/.github/workflows/verify-keystore.yml
@@ -16,6 +16,20 @@ jobs:
         run: |
           echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > mg-build-release-key.keystore
 
+      - name: Check Directory Contents and Keystore Size
+        run: |
+          echo "Listing current directory contents:"
+          ls -la
+
+          echo "Checking the size of the keystore file:"
+          if [ -s mg-build-release-key.keystore ]; then
+            echo "Keystore file is not empty. Size:"
+            du -h mg-build-release-key.keystore
+          else
+            echo "Keystore file is empty."
+            exit 1  # Fail the workflow if the file is empty
+          fi
+
       - name: List Keystore Contents
         run: |
           keytool -list -v -keystore mg-build-release-key.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
